
###############################################################################
####################### Monitoring Stack For Docker-Swarm #####################
###############################################################################

version: '3.2'

services:

  prometheus:
    image: prom/prometheus:latest
    ports:
      - published: 9090
        target: 9090
        protocol: tcp
        mode: host
    volumes:
      - /opt/data/etc/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /opt/data/prometheus:/prometheus:rw
    deploy:
      placement:
        constraints:
          - node.labels.type == prometheus

  grafana:
    image: grafana/grafana
    ports:
      - published: 3000
        target: 3000
        protocol: tcp
        mode: host
    environment:
      - GF_SERVER_DOMAIN=server.com #example
      - GF_SERVER_ROOT_URL=server.com #example
    volumes:
      - /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem:/etc/ssl/certs/ca-certificates.crt:ro # for use certificate ssl
      - /opt/data/grafana/lib:/var/lib/grafana:rw
      - /opt/data/grafana/etc:/etc/grafana:rw
    deploy:
      placement:
        constraints:
          - node.labels.type == prometheus

  cadvisor:
    image: google/cadvisor
    ports:
      - published: 8044
        target: 8080
        protocol: tcp
        mode: host
    hostname: '{{.Node.ID}}'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      update_config:
        parallelism: 3
        monitor: 2m
        max_failure_ratio: 0.3
        failure_action: rollback
        delay: 30s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  zabbix-backend:
        image: zabbix/zabbix-server-pgsql:centos-4.2-latest
        volumes:
            - /opt/externalscripts:/usr/lib/zabbix/externalscripts:rw # for use external scripts
        depends_on:
            - zabbix-db
        environment:
            - DB_SERVER_HOST=zabbix-db
            - DB_SERVER_PORT=5432
            - POSTGRES_USER=zabbix
            - POSTGRES_PASSWORD=zabbix
            - POSTGRES_DB=zabbix
            - ZBX_DEBUGLEVEL=4 #level_debug
        ports:
          - published: 10051
            target: 10051
            protocol: tcp
            mode: host
        deploy:
          placement:
            constraints:
              - node.labels.type == prometheus

    zabbix-frontend:
        image: zabbix/zabbix-web-nginx-pgsql:centos-4.2-latest
        depends_on:
            - zabbix-backend
        environment:
            - DB_SERVER_HOST=zabbix-db
            - DB_SERVER_PORT=5432
            - POSTGRES_USER=zabbix
            - POSTGRES_PASSWORD=zabbix
            - POSTGRES_DB=zabbix
            - ZBX_SERVER_HOST=zabbix-backend
            - PHP_TZ=Europe/Riga # use TZ for your location
        ports:
          - published: 8082
            target: 80
            protocol: tcp
            mode: host
        deploy:
          placement:
            constraints:
              - node.labels.type == prometheus

    zabbix-agent:
        image: zabbix/zabbix-agent:centos-4.2-latest
        depends_on:
            - zabbix-backend
        environment: 
            - ZBX_SERVER_HOST=server.domain.com,gateway # use zabbix server
            - ZBX_SERVER_PORT=10051
            - ZBX_ACTIVE_ALLOW=false
        ports:
          - published: 10050
            target: 10050
            protocol: tcp
            mode: host
        volumes:
            - /:/rootfs:ro
        deploy:
          mode: global

    zabbix-db:
        image: postgres
        volumes:
            - /opt/zbx_db/pgsql:/var/lib/postgresql/data/pgdata # for DB PostgreSQL
        environment:
            - POSTGRES_USER=zabbix
            - POSTGRES_PASSWORD=zabbix
            - POSTGRES_DB=zabbix
            - PGDATA=/var/lib/postgresql/data/pgdata
        deploy:
          placement:
            constraints:
              - node.labels.type == prometheus
